//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centapp.Cowbell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Centapp.Cowbell.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate app!.
        /// </summary>
        internal static string rateAppButton {
            get {
                return ResourceManager.GetString("rateAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars :)
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        internal static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our app!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        internal static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        internal static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying {0}?.
        /// </summary>
        internal static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        internal static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
    }
}
